stages:        
  - test
  - build
  - deploy

test_frontend:
  stage: test
  image: public.ecr.aws/docker/library/node:lts-alpine
  script:
    - cd frontend
    - npm install
    - npm run test

build_frontend:
  stage: build
  needs: ["test_frontend"]
  image: 
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo ...
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "frontend"
      --dockerfile "frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  artifacts:
    paths:
      - frontend/dist
