version: "3.7"

services:
 frontend:
  container_name: vue-frontend
  depends_on:
   - backend
  build:
   context: ./frontend
   dockerfile: Dockerfile
  ports:
   - "3000:80"
  volumes:
  - ./frontend/:/app
  restart: unless-stopped
  networks:
   - app

 backend:
  container_name: springboot-backend
  depends_on:
   - postgres
  environment:
   SPRING_PROFILES_ACTIVE: dev
   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_dev
   SPRING_DATASOURCE_USERNAME: dev
   SPRING_DATASOURCE_PASSWORD: dev_pw
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - "3001:8080"
  restart: unless-stopped
  networks:
   - app

 postgres:
  container_name: postgres-database
  image: postgres:16
  environment:
   POSTGRES_DB: db_dev
   POSTGRES_USER: dev
   POSTGRES_PASSWORD: dev_pw
  volumes:
   - postgres_data:/var/lib/postgresql/data
  restart: unless-stopped
  ports:
   - "5432:5432"
  networks:
   - app

volumes:
 postgres_data:

networks:
 app:
  driver: bridge
