version: "3.7" 

services: 
 frontend: 
  container_name: vue-frontend
  depends_on:
   - backend
  build: 
   context: ./frontend/ 
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  volumes: 
  - ./frontend/:/app 
  restart: unless-stopped

 backend:
  container_name: springboot-backend
  depends_on:
   - postgres
  env_file:
   - .env.dev
  environment:
   SPRING_PROFILES_ACTIVE: dev
   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_dev
   SPRING_DATASOURCE_USERNAME: dev
   SPRING_DATASOURCE_PASSWORD: dev_pw
  build:
   context: ./backend/
   dockerfile: Dockerfile
   target: development
  ports:
   - "8081:8081"
  volumes:
   - ./backend/:/app
  restart: unless-stopped



 postgres:
  environment:
   POSTGRES_DB: db_dev
   POSTGRES_USERNAME: dev
   POSTGRES_PASSWORD: dev_pw
  image: postgres:16
  container_name: postgres-database
  volumes:
   - postgres_data:/var/lib/postgresql/data
  restart: unless-stopped
  ports:
   - "5432:5432"

volumes:
 postgres_data:

networks:
 backend_network:
  driver: bridge