version: "3.7"

services:
  frontend:
   container_name: vue-frontend
   image: swtp04/vue-frontend:latest
   ports:
    - 172.26.92.83:3000:3000
   restart: unless-stopped
  
  backend:
   container_name: springboot-backend
   image: swtp04/springboot-backend:latest
   environment:
     SPRING_PROFILES_ACTIVE: prod
     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
     SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
     SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
   ports:
    - 172.26.92.83:3001:3001
   restart: unless-stopped
   depends_on:
    - postgres
   environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/backend_database
    SPRING_DATASOURCE_USERNAME: swtp
    SPRING_DATASOURCE_PASSWORD: brunchPaprika2023

  postgres:
   image: postgres:16
   container_name: postgres-database
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USERNAME}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   volumes:
    - postgres_data:/var/lib/postgresql/data
   restart: unless-stopped
   ports:
     - 5432:5432

volumes:
 postgres_data:
