version: "3.7"

services:
  frontend:
   container_name: vue-frontend
   image: swtp04/vue-frontend:latest
   ports:
    - 172.26.92.83:3000:80
   restart: unless-stopped
  
  backend:
   container_name: springboot-backend
   image: swtp04/springboot-backend:latest
   environment:
     SPRING_PROFILES_ACTIVE: prod
     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
     SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
     SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
   ports:
    - 172.26.92.83:3001:8080
   restart: unless-stopped


  postgres:
   image: postgres:16
   container_name: postgres-database
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USERNAME}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   volumes:
    - postgres_data:/var/lib/postgresql/data
   restart: unless-stopped

volumes:
 postgres_data:
