version: "3.7"

services:
  frontend:
   container_name: vue-frontend
   image: swtp04/vue-frontend:latest
   ports:
    - 172.26.92.83:3000:80
   restart: unless-stopped
  
  backend:
   container_name: springboot-backend
   image: swtp04/springboot-backend:latest
   ports:
    - 172.26.92.83:3001:8080
   restart: unless-stopped
   environment:
    - SPRING_PROFILES_ACTIVE=prod


  postgres:
   env_file:
    - .env.prod
   image: postgres:16
   container_name: postgres-database
   volumes:
    - postgres_data:/var/lib/postgresql/data
   restart: unless-stopped

volumes:
 postgres_data:
