version: "3.7"

services:
  frontend:
   container_name: vue-frontend
   image: swtp04/vue-frontend:latest
   ports:
    - 172.26.92.83:3000:80
   depends_on:
    - backend
   restart: unless-stopped
   environment:
    VUE_APP_API_URL: 172.26.92.83:3000
   networks:
    - app
  
  backend:
   container_name: springboot-backend
   image: swtp04/springboot-backend:latest
   ports:
    - 172.26.92.83:3001:8080
   depends_on:
    - postgres
   restart: unless-stopped
   environment:
    SPRING_PROFILES_ACTIVE: prod
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/your_database_name
    SPRING_DATASOURCE_USERNAME: your_username
    SPRING_DATASOURCE_PASSWORD: your_password
#   gitlab secret variables should be used
    JWT_SECRET: "kdcg/HWhPwXlI0IzwNAph97Vwv7mnQ5tM0EH//MmSjXrbGkFTB1jCupER02sJQykbmBHg8TahS7YIl2tJ8uh4A=="
    JWT_EXPIRATION: 3600000
    JWT_HEADER: Authorization
    JWT_PREFIX: "Bearer "
    OFFICE_USERNAME: Studienbüro
    OFFICE_PASSWORD: 1234
    COMMITTEE_USERNAME: Prüfungsausschuss
    COMMITTEE_PASSWORD: 1234
   volumes:
    - pdf_files:/app/pdf-files
   networks:
    - app

  postgres:
   image: postgres:16
   container_name: postgres-database
   environment:
    POSTGRES_DB: your_database_name
    POSTGRES_USER: your_username
    POSTGRES_PASSWORD: your_password
   volumes:
    - postgres_data:/var/lib/postgresql/data
   networks:
    - app
   ports:
    - 172.26.92.83:5432:5432
   restart: unless-stopped

networks:
 app:
  driver: bridge
  ipam:
   config:
    - subnet: 172.18.0.0/24


volumes:
 postgres_data:
 pdf_files:
