version: "3.7" 
services: 
 frontend: 
  container_name: vue-frontend 
  build: 
   context: ./frontend/ 
   dockerfile: Dockerfile 
   target: development 
  ports:
   - 8080:8080
  volumes: 
  - ./frontend/:/app 
  restart: unless-stopped