version: "3.7" 

services: 
 frontend: 
  container_name: vue-frontend 
  build: 
   context: ./frontend/ 
   dockerfile: Dockerfile 
   target: development 
  ports:
   - 80:80
  volumes: 
  - ./frontend/:/app 
  restart: unless-stopped

 backend:
  container_name: springboot-backend
  build:
   context: ./backend/
   dockerfile: Dockerfile
   target: build
  ports:
   - 8080:8080
  volumes:
   - ./backend/:/app
  restart: unless-stopped
  environment:
   - SPRING_PROFILES_ACTIVE=dev


 postgres:
  env_file:
   - .env.dev
  image: postgres:16
  container_name: postgres-database
  volumes:
   - postgres_data:/var/lib/postgresql/data
  restart: unless-stopped

volumes:
 postgres_data:
