version: "3.7"

services:
 frontend:
  container_name: vue-frontend
  depends_on:
   - backend
  environment:
   VUE_APP_API_URL: localhost:3000
  build:
   context: ./frontend
   dockerfile: Dockerfile
  ports:
   - "3000:80"
  volumes:
  - ./frontend/:/app
  restart: unless-stopped
  networks:
   - app

 backend:
  container_name: springboot-backend
  depends_on:
   - postgres
  environment:
   SPRING_PROFILES_ACTIVE: dev
   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_dev
   SPRING_DATASOURCE_USERNAME: dev
   SPRING_DATASOURCE_PASSWORD: dev_pw
   # set in application.properties:
#   OFFICE_USERNAME: office
#   OFFICE_PASSWORD: pw_office
#   COMMITTEE_USERNAME: committee
#   COMMITTEE_PASSWORD: pw_committee
#   JWT_SECRET: "kdcg/HWhPwXlI0IzwNAph97Vwv7mnQ5tM0EH//MmSjXrbGkFTB1jCupER02sJQykbmBHg8TahS7YIl2tJ8uh4A=="
#   JWT_EXPIRATION: 3600000
#   JWT_HEADER: Authorization
#   JWT_PREFIX: "Bearer "
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - "3001:8080"
  restart: unless-stopped
  volumes:
   - pdf_files:/app/pdf-files
  networks:
   - app

 postgres:
  container_name: postgres-database
  image: postgres:16
  environment:
   POSTGRES_DB: db_dev
   POSTGRES_USER: dev
   POSTGRES_PASSWORD: dev_pw
  restart: unless-stopped
  ports:
   - "5432:5432"
  networks:
   - app


networks:
 app:
  driver: bridge

volumes:
 pdf_files: