version: "3.7"

services:
  frontend:
   container_name: vue-frontend
   image: swtp04/vue-frontend:latest
   ports:
    - 172.26.92.83:3000:80
   depends_on:
    - backend
   restart: unless-stopped
   networks:
    - frontend_backend_network
  
  backend:
   container_name: springboot-backend
   image: swtp04/springboot-backend:latest
   ports:
    - 172.26.92.83:3001:8080
   depends_on:
    - postgres
   restart: unless-stopped
   environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/your_database_name
    SPRING_DATASOURCE_USERNAME: your_username
    SPRING_DATASOURCE_PASSWORD: your_password
   networks:
    - backend_db_network
    - frontend_backend_network

  postgres:
   image: postgres:16
   environment:
    POSTGRES_DB: your_database_name
    POSTGRES_USER: your_username
    POSTGRES_PASSWORD: your_password
   networks:
    - backend_db_network

networks:
 backend_db_network:
  driver: bridge
  ipam:
   config:
    - subnet: 172.17.0.0/25
 frontend_backend_network:
  driver: bridge
  ipam:
   config:
    - subnet: 172.17.1.0/25

