spring:
  datasource:
    url: ""
    username: ""
    password: ""
  sql:
    init:
      encoding: UTF-8
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  profiles:
    active: dev

# JWT token configuration
jwt:
  secret: kdcg/HWhPwXlI0IzwNAph97Vwv7mnQ5tM0EH//MmSjXrbGkFTB1jCupER02sJQykbmBHg8TahS7YIl2tJ8uh4A==
  expiration: 3600000
  header: Authorization
  prefix: "Bearer "

# Default users in database
office:
  username: office
  password: pw_office

committee:
  username: committee
  password: pw_committee